### ISSUE TITLE
Restore - Handled error

### ISSUE THREAD

**Issue by SamuraiTheNinja** [MonitoringSolutionsInc/DatabaseBackupTool#22]
When restoring, sometimes the restore freezes at near completion for a little bit then a pop up occurs with a title saying something about SQL Express. That pop up is frozen and has no info in the center text box. This frozen text box is related to calling the ErrorForm from a BackGroundWorker (as it's in a different thread). Not sure what the error  is (since it's not displaying properly, and since it's being "handled") 

This happens to me only some times when restoring, usually the file set is close to 100 databases it's restoring

**Comment by JazzGlobal** [comment]
Working on a logger that should fix this problem.

**Comment by JazzGlobal** [comment]
Log developed. Will open a pull request to integrate.
