### ISSUE TITLE
Add Command Line

### ISSUE THREAD

**Issue by JazzGlobal** [MonitoringSolutionsInc/DatabaseBackupTool#46]
add command line features to handle specific cases that can be scripted. 

Example Problem: Backup last 6 months of data with config dbs
Example Command: backup -tmonths 6 -config true

**Comment by JazzGlobal** [comment]
@SamuraiTheNinja  

I have a WIP utility that achieves what I want. Should it be added to this repo or should we create a new one? It does not rely on the DatabaseBackupTool, only SQLConnector for now.

**Comment by SamuraiTheNinja** [comment]
WIP being "Work In Progress" I assume. Is the goal to integrate it into the backup and restore tool? If so then yeah I'd say add it to this repo, otherwise it should probably be separate. My preference would be to integrate it and have it in its own branch for a while

**Comment by JazzGlobal** [comment]
@SamuraiTheNinja 
Correct, WIP = Work in progress. I was initially wanting it to be "integrated" but I think it'll be a more robust tool if it is developed externally. It's still something I'm exploring / weighing options. Will put it into a new repo for the time being and then we can review it at a later time since it isn't the highest priority item at the moment. I was able to throw some of it together over the weekend and then threw it into a CLI format this morning.
