### ISSUE TITLE
Obfuscate executable

### ISSUE THREAD

**Issue by SamuraiTheNinja** [MonitoringSolutionsInc/DatabaseBackupTool#58]

**Comment by SamuraiTheNinja** [comment]
@JazzGlobal I know the issue #55 exists but do we actually plan to eventually make this code private? It doesn't contain anything proprietary I don't think, does it? 

Regardless of whether or not this repos is private, do we need to both obfuscating it?

**Comment by JazzGlobal** [comment]
@SamuraiTheNinja I don't recall why we keep it private other than client access. We can likely handle distribution of it ourselves via MDT. 

There isn't anything special inside the tool, it doesn't need obfuscating. Unless Mike disagrees.

**Comment by JazzGlobal** [comment]
> 

Did Mike say we should obfuscate this? @SamuraiTheNinja
