### ISSUE TITLE
Use a TTF as primary font

### ISSUE THREAD

**Issue by SamuraiTheNinja** [MonitoringSolutionsInc/DatabaseBackupTool#79]
Switch the application's font to a TTF (True Type Font) so it looks better across more displays. Have recently scaled my display and this tool along with the Csharp version of Generate Scans tool's text look like butt.

**Comment by SamuraiTheNinja** [comment]
After further investigation, TTF is a type of font which contains information on how it should be displayed. ClearType on the other hand is a text rendering solution developed by microsoft, it works with all fonts since ClearType is a separate layer. It will take the output from whatever font and then modify it to help it look the best on any given display. 
Furtheremore, there exits OTF (Open Type Font) which is the latest font standard. Unfortunately OTF is not supported in Winforms apps. Seems like there's no need to modify the font of our apps at all. I  probably should have just re-run the ClearType setup

**Comment by JazzGlobal** [comment]
Fixed since ClearType is available and enabled by default on Windows 10 computers.
